Repository Questory04/Questory_BE, pull requests merged in 2025-05, with the labels that each got.

#8 [FEAT] #7 - 회원가입 시 이메일 인증 기능 구현
  pom.xml
  src/main/java/com/ssafy/questory/common/util/RedisUtil.java
  src/main/java/com/ssafy/questory/controller/MemberController.java
  src/main/java/com/ssafy/questory/dto/request/member/EmailVerifyRequestDto.java
  src/main/java/com/ssafy/questory/dto/request/member/MemberEmailRequestDto.java
  src/main/java/com/ssafy/questory/service/MailSendService.java
  src/main/java/com/ssafy/questory/service/mail/MailContentBuilder.java
  src/main/java/com/ssafy/questory/service/mail/MailSendService.java
  src/main/java/com/ssafy/questory/service/mail/PasswordResetService.java
  src/main/java/com/ssafy/questory/service/mail/VerifyService.java
  src/test/java/com/ssafy/questory/service/MailSendServiceTest.java
Labels: enhancement

#10 [FEAT] #9 - Swagger 적용
  pom.xml
  src/main/java/com/ssafy/questory/config/SwaggerConfig.java
  src/main/java/com/ssafy/questory/controller/MemberController.java
Labels: enhancement

#12 [FEAT] #11 - 전역 예외 처리
  src/main/java/com/ssafy/questory/common/exception/CustomException.java
  src/main/java/com/ssafy/questory/common/exception/ErrorCode.java
  src/main/java/com/ssafy/questory/common/exception/GlobalExceptionHandler.java
  src/main/java/com/ssafy/questory/dto/response/error/ErrorResponseDto.java
  src/main/java/com/ssafy/questory/service/MemberService.java
  src/main/java/com/ssafy/questory/service/mail/PasswordResetService.java
  src/main/java/com/ssafy/questory/service/mail/VerifyService.java
  src/test/java/com/ssafy/questory/service/MemberServiceTest.java
Labels: enhancement

#15 [FEAT] #14 - 내 정보 관련 CRUD
  src/main/java/com/ssafy/questory/config/jwt/CustomUserDetailsService.java
  src/main/java/com/ssafy/questory/controller/MemberAuthController.java
  src/main/java/com/ssafy/questory/domain/Member.java
  src/main/java/com/ssafy/questory/domain/SecurityMember.java
  src/main/java/com/ssafy/questory/dto/request/member/MemberModifyPasswordRequestDto.java
  src/main/java/com/ssafy/questory/dto/request/member/MemberModifyRequestDto.java
  src/main/java/com/ssafy/questory/dto/response/member/auth/MemberInfoResponseDto.java
  src/main/java/com/ssafy/questory/repository/MemberRepository.java
  src/main/java/com/ssafy/questory/repository/SecurityMemberRepository.java
  src/main/java/com/ssafy/questory/service/MemberAuthService.java
  src/main/resources/mappers/Member.xml
  src/main/resources/mappers/SecureMember.xml
  src/test/java/com/ssafy/questory/service/MemberAuthServiceTest.java
Labels: enhancement

#18 #5 get stamps list
  .gitignore
  pom.xml
  src/main/java/com/ssafy/questory/common/exception/ErrorCode.java
  src/main/java/com/ssafy/questory/controller/StampController.java
  src/main/java/com/ssafy/questory/domain/Stamp.java
  src/main/java/com/ssafy/questory/dto/response/stamp/StampsResponseDto.java
  src/main/java/com/ssafy/questory/repository/StampRepository.java
  src/main/java/com/ssafy/questory/service/StampService.java
  src/main/resources/mappers/Stamp.xml
  src/main/resources/sql/questory.sql
  src/test/java/com/ssafy/questory/service/StampServiceTest.java
Labels: enhancement

#19 [FEAT] #16 - 친구 관련 CRUD
  src/main/java/com/ssafy/questory/controller/FollowController.java
  src/main/java/com/ssafy/questory/domain/FollowStatus.java
  src/main/java/com/ssafy/questory/domain/Friend.java
  src/main/java/com/ssafy/questory/domain/Member.java
  src/main/java/com/ssafy/questory/dto/request/friend/FriendStatusRequestDto.java
  src/main/java/com/ssafy/questory/dto/response/friend/FollowResponseDto.java
  src/main/java/com/ssafy/questory/repository/FriendRepository.java
  src/main/java/com/ssafy/questory/service/FriendService.java
  src/main/resources/mappers/Friend.xml
  src/test/java/com/ssafy/questory/service/FriendServiceTest.java
Labels: enhancement

#21 [FEAT] #5 - 보유한 스탬프 목록 조회
  src/main/java/com/ssafy/questory/dto/response/stamp/StampsResponseDto.java
  src/main/resources/mappers/Stamp.xml
  src/test/java/com/ssafy/questory/service/StampServiceTest.java
Labels: enhancement

#23 [FEAT] #22 - 칭호 관련 CR
  src/main/java/com/ssafy/questory/controller/TitleController.java
  src/main/java/com/ssafy/questory/domain/MemberTitle.java
  src/main/java/com/ssafy/questory/domain/Title.java
  src/main/java/com/ssafy/questory/dto/request/title/TitleEarnRequestDto.java
  src/main/java/com/ssafy/questory/dto/response/title/TitleInfoResponseDto.java
  src/main/java/com/ssafy/questory/repository/TitleMemberRepository.java
  src/main/java/com/ssafy/questory/service/TitleService.java
  src/main/resources/mappers/Title.xml
  src/test/java/com/ssafy/questory/service/TitleServiceTest.java
Labels: enhancement

#25 [FEAT] #17 - 퀘스트 관련 기능 CRUD
  src/main/java/com/ssafy/questory/common/exception/ErrorCode.java
  src/main/java/com/ssafy/questory/controller/QuestController.java
  src/main/java/com/ssafy/questory/dto/request/quest/QuestRequestDto.java
  src/main/java/com/ssafy/questory/dto/response/quest/QuestsResponseDto.java
  src/main/java/com/ssafy/questory/repository/QuestRepository.java
  src/main/java/com/ssafy/questory/service/QuestService.java
  src/main/resources/mappers/Quest.xml
  src/test/java/com/ssafy/questory/service/QuestServiceTest.java
Labels: enhancement

#27 [FEAT] #24 - 탈퇴한 회원 로그인, 회원가입 제한
  src/main/java/com/ssafy/questory/common/exception/ErrorCode.java
  src/main/java/com/ssafy/questory/service/MemberService.java
Labels: bug, enhancement

#30 [FEAT] 관광지 검색 기능 구현
  src/main/java/com/ssafy/questory/common/exception/ErrorCode.java
  src/main/java/com/ssafy/questory/controller/QuestController.java
  src/main/java/com/ssafy/questory/dto/response/quest/AttractionResponseDto.java
  src/main/java/com/ssafy/questory/repository/QuestRepository.java
  src/main/java/com/ssafy/questory/service/QuestService.java
  src/main/resources/mappers/Quest.xml
Labels: enhancement

#31 [FEAT] #20 - 여행 계획 관련 CRUD 구현
  src/main/java/com/ssafy/questory/common/exception/ErrorCode.java
  src/main/java/com/ssafy/questory/controller/PlanController.java
  src/main/java/com/ssafy/questory/domain/Plan.java
  src/main/java/com/ssafy/questory/domain/Route.java
  src/main/java/com/ssafy/questory/dto/request/plan/PlanCreateRequestDto.java
  src/main/java/com/ssafy/questory/dto/request/plan/PlanDeleteRequestDto.java
  src/main/java/com/ssafy/questory/dto/request/plan/PlanUpdateRequestDto.java
  src/main/java/com/ssafy/questory/dto/response/plan/PlanInfoResponseDto.java
  src/main/java/com/ssafy/questory/repository/PlanRepository.java
  src/main/java/com/ssafy/questory/repository/PlanRoutesRepository.java
  src/main/java/com/ssafy/questory/service/PlanService.java
  src/main/resources/mappers/PlanRoute.xml
  src/main/resources/mappers/plan.xml
  src/test/java/com/ssafy/questory/service/PlanServiceTest.java
Labels: enhancement

#34 [MODIFY] 난이도 별 스탬프 전체 목록 조회 기능 구현
  src/main/java/com/ssafy/questory/controller/StampController.java
  src/main/java/com/ssafy/questory/repository/StampRepository.java
  src/main/java/com/ssafy/questory/service/StampService.java
  src/main/resources/mappers/Stamp.xml
  src/main/resources/sql/questory.sql
  src/test/java/com/ssafy/questory/service/StampServiceTest.java
Labels: enhancement

#38 [FEAT] #32 - 경로 공유 및 저장 기능 구현
  src/main/java/com/ssafy/questory/common/exception/ErrorCode.java
  src/main/java/com/ssafy/questory/controller/PlanController.java
  src/main/java/com/ssafy/questory/domain/Plan.java
  src/main/java/com/ssafy/questory/domain/SavedPlan.java
  src/main/java/com/ssafy/questory/dto/response/plan/PlanInfoResponseDto.java
  src/main/java/com/ssafy/questory/repository/PlanRepository.java
  src/main/java/com/ssafy/questory/repository/SavedRepository.java
  src/main/java/com/ssafy/questory/service/PlanService.java
  src/main/resources/mappers/Saved.xml
  src/main/resources/mappers/plan.xml
  src/main/resources/sql/questory.sql
Labels: enhancement

#39 [MODIFY] #37 - 난이도 별 퀘스트 전체 목록 조회
  src/main/java/com/ssafy/questory/controller/QuestController.java
  src/main/java/com/ssafy/questory/repository/QuestRepository.java
  src/main/java/com/ssafy/questory/service/QuestService.java
  src/main/resources/mappers/Quest.xml
  src/test/java/com/ssafy/questory/service/QuestServiceTest.java
Labels: enhancement

#42 [FIX] 누락된 테이블 생성 쿼리문 추가
  src/main/resources/sql/questory.sql
Labels: bug

#45 [FEAT] #44 - 이메일을 통한 유저 검색 기능 구현
  src/main/java/com/ssafy/questory/controller/MemberController.java
  src/main/java/com/ssafy/questory/domain/Member.java
  src/main/java/com/ssafy/questory/dto/request/member/MemberSearchRequestDto.java
  src/main/java/com/ssafy/questory/dto/response/member/MemberSearchResponseDto.java
  src/main/java/com/ssafy/questory/repository/MemberRepository.java
  src/main/java/com/ssafy/questory/service/MemberService.java
  src/main/resources/mappers/Member.xml
  src/test/java/com/ssafy/questory/service/MemberServiceTest.java
  src/test/java/com/ssafy/questory/service/PlanServiceTest.java
Labels: enhancement

#47 [MODIFY] #40 - 관광지 검색 기능 구현
  src/main/java/com/ssafy/questory/common/exception/ErrorCode.java
  src/main/java/com/ssafy/questory/controller/AttractionController.java
  src/main/java/com/ssafy/questory/controller/QuestController.java
  src/main/java/com/ssafy/questory/dto/response/attraction/AttractionResponseDto.java
  src/main/java/com/ssafy/questory/dto/response/quest/QuestResponseDto.java
  src/main/java/com/ssafy/questory/repository/AttractionRepository.java
  src/main/java/com/ssafy/questory/repository/QuestRepository.java
  src/main/java/com/ssafy/questory/service/AttractionService.java
  src/main/java/com/ssafy/questory/service/QuestService.java
  src/main/resources/mappers/Attraction.xml
  src/main/resources/mappers/Quest.xml
Labels: enhancement

#49 [FEAT] #46 - 보낸 친구 요청 목록 조회 기능 구현
  src/main/java/com/ssafy/questory/controller/FollowController.java
  src/main/java/com/ssafy/questory/domain/Friend.java
  src/main/java/com/ssafy/questory/dto/response/friend/FollowResponseDto.java
  src/main/java/com/ssafy/questory/repository/FriendRepository.java
  src/main/java/com/ssafy/questory/service/FriendService.java
  src/main/resources/mappers/Friend.xml
  src/test/java/com/ssafy/questory/service/FriendServiceTest.java
Labels: enhancement

#50 [FEAT] #48 - 생성한 퀘스트 리스트 조회 기능 구현
  src/main/java/com/ssafy/questory/controller/QuestController.java
  src/main/java/com/ssafy/questory/domain/Stamp.java
  src/main/java/com/ssafy/questory/dto/request/quest/QuestRequestDto.java
  src/main/java/com/ssafy/questory/dto/response/attraction/AttractionResponseDto.java
  src/main/java/com/ssafy/questory/dto/response/quest/QuestResponseDto.java
  src/main/java/com/ssafy/questory/dto/response/quest/QuestsResponseDto.java
  src/main/java/com/ssafy/questory/dto/response/stamp/StampsResponseDto.java
  src/main/java/com/ssafy/questory/repository/QuestRepository.java
  src/main/java/com/ssafy/questory/service/QuestService.java
  src/main/resources/mappers/Quest.xml
  src/test/java/com/ssafy/questory/service/QuestServiceTest.java
Labels: enhancement

#57 [FEAT] #56 - 퀘스트 시작 기능, 퀘스트 완료 기능 구현
  src/main/java/com/ssafy/questory/common/exception/ErrorCode.java
  src/main/java/com/ssafy/questory/controller/QuestController.java
  src/main/java/com/ssafy/questory/dto/request/quest/QuestPositionRequestDto.java
  src/main/java/com/ssafy/questory/dto/response/quest/QuestsResponseDto.java
  src/main/java/com/ssafy/questory/repository/QuestRepository.java
  src/main/java/com/ssafy/questory/service/QuestService.java
  src/main/resources/mappers/Quest.xml
  src/main/resources/sql/questory.sql
Labels: enhancement

#59 [FIX] #58 - 전체 퀘스트 목록 조회
  src/main/resources/mappers/Quest.xml
Labels: bug

#62 [MODIFY] #60 - 퀘스트 완료 기능 구현
  src/main/java/com/ssafy/questory/domain/DifficultyStatus.java
  src/main/java/com/ssafy/questory/repository/MemberRepository.java
  src/main/java/com/ssafy/questory/repository/QuestRepository.java
  src/main/java/com/ssafy/questory/service/MemberAuthService.java
  src/main/java/com/ssafy/questory/service/QuestService.java
  src/main/resources/mappers/Member.xml
  src/main/resources/mappers/Quest.xml
Labels: enhancement

#66 [FEAT] #65 - gpt 챗봇 구현
  pom.xml
  src/main/java/com/ssafy/questory/config/OpenAiProperties.java
  src/main/java/com/ssafy/questory/controller/ChatController.java
  src/main/java/com/ssafy/questory/domain/ChatMessage.java
  src/main/java/com/ssafy/questory/dto/request/chat/ChatRequestDto.java
  src/main/java/com/ssafy/questory/service/ChatGptService.java
Labels: enhancement

#70 [FEAT] #63 - 여행 계획 세우기 관련 기능 구현
  src/main/java/com/ssafy/questory/controller/PlanController.java
  src/main/java/com/ssafy/questory/controller/RouteController.java
  src/main/java/com/ssafy/questory/domain/PlanStatus.java
  src/main/java/com/ssafy/questory/dto/request/route/RouteCreateRequestDto.java
  src/main/java/com/ssafy/questory/dto/response/plan/PlanCreateResponseDto.java
  src/main/java/com/ssafy/questory/dto/response/plan/PlansListResponseDto.java
  src/main/java/com/ssafy/questory/dto/response/route/RouteResponseDto.java
  src/main/java/com/ssafy/questory/repository/PlanRepository.java
  src/main/java/com/ssafy/questory/repository/RouteRepository.java
  src/main/java/com/ssafy/questory/service/PlanService.java
  src/main/java/com/ssafy/questory/service/RouteService.java
  src/main/resources/mappers/Route.xml
  src/main/resources/mappers/plan.xml
Labels: enhancement

#72 [FEAT] #71 - 여행 계획 전체 조회 기능 구현
  src/main/java/com/ssafy/questory/controller/PlanController.java
  src/main/java/com/ssafy/questory/repository/PlanRepository.java
  src/main/java/com/ssafy/questory/service/PlanService.java
  src/main/resources/mappers/plan.xml
Labels: enhancement

#77 [FIX] #75 - response dto 수정
  src/main/java/com/ssafy/questory/dto/response/quest/QuestRecommendationResponseDto.java
  src/main/resources/mappers/Quest.xml
Labels: bug, enhancement

#81 [FEAT] #80 - 메인페이지 추천 퀘스트 리스트 조회 기능 구현
  src/main/java/com/ssafy/questory/dto/response/quest/QuestRecommendationResponseDto.java
  src/main/resources/mappers/Quest.xml
  src/main/resources/sql/questory.sql
Labels: enhancement
